### ISSUE TITLE
[webpkgserver] ignore third party subresources preloading

### ISSUE THREAD

**Issue by sangotaro** [google/webpackager#90]
Our site uses a third party resource preloading (AMP v0.js). 

```
<link rel="preload" href="https://cdn.ampproject.org/lts/v0.js" as="script">
```

webpkgserver will attempt to fetch that resource, which will result in the following error.

```
2021/06/25 18:07:55 processing https://cdn.ampproject.org/lts/v0.js ...
2021/06/25 18:07:55 error with processing https://cdn.ampproject.org/lts/v0.js: fetch: URL doesn't match the fetch targets
```

Is there any way to ignore this preload?

**Comment by twifkak** [comment]
My understanding is that this URL is not fetched, and it is omitted from the outer `Link` header. It sounds like the bug here is to better document that behavior, and to clarify the text of that error message (or maybe just omit it entirely, since it's not an error).

Details:

The error message comes from here:
https://github.com/google/webpackager/blob/c7597c58f5e83513153ff8b77ad2e7486bd2c597/fetch/with_selector.go#L42-L44
and the early return means the inner FetchClient.Do call is never called.

The default `false` value of this config field:
https://github.com/google/webpackager/blob/c7597c58f5e83513153ff8b77ad2e7486bd2c597/cmd/webpkgserver/webpkgserver.example.toml#L147
means that subresources without SXGs will be subsequently omitted here:
https://github.com/google/webpackager/blob/c7597c58f5e83513153ff8b77ad2e7486bd2c597/exchange/response.go#L103-L104

**Comment by sangotaro** [comment]
Thank you for the detailed explanation of the log and solving the problem.
