### ISSUE TITLE
500 error occurs when ocsp cache does not exist

### ISSUE THREAD

**Issue by ka2jun8** [google/webpackager#97]
I think `webpkgserver` should return 404 error if the cache does not exist.
(Looking here, it looks like it's supposed to be.)
https://github.com/google/webpackager/blob/main/server/handler.go#L119-L122

However, in fact, "No such file or directory" occurred in `ioutil.ReadFile`, and webpkgserver seems to be getting a 500 error.
https://github.com/google/webpackager/blob/main/certchain/certmanager/multicert_disk_cache.go#L115-L118

I didn't know how `certmanager.ErrNotFound` was used, but what about returning certmanager.ErrNotFound here?
https://github.com/google/webpackager/blob/main/certchain/certchainutil/certchainutil.go#L45-L48

**Comment by banaag** [comment]
Thank you very much for your feedback.
Could you help me understand why you got the "No such file or directory" error? Was it because the CertDir in the multi-cert disk cache (https://github.com/google/webpackager/blob/main/certchain/certmanager/multicert_disk_cache.go#L53) was not configured?

**Comment by ka2jun8** [comment]
I'm sorry, I didn't explain enough.
`CacheDir` is configured, like `CacheDir = '/tmp/cache'`.

Due to our private circumstances, we had to replace the certificate with another one.
So we changed the certificate to refer to another one and restarted webpkgserver once.
I think the cache was cleared at that time.

However, googlebots access the cert-url bundled with sxg certificated in the past.
https://github.com/google/webpackager/blob/main/exchange/factory.go#L65
They try to access the cache with a past cert hash.
However, there is no cache created from past certificates in `/tmp/cache`.

By the way, because googlebots came to pick up new sxg,
they can access new cache without any problem and users seem to be able to see new sxg cache on google search results now.
Therefore, the reported errors are not critical to us.
(I do not know why but bots are acccessing old one sometimes even now, errors have occured.)

example: 
`${origin}/webpkg/cert/${old_hash}` 500 (no such files ...)
`${origin}/webpkg/cert/${new_hash}` 200 (ok)

**Comment by banaag** [comment]
Thanks for providing more details.  It looks like you have a case where the cert stored in webpkgcache got stale because of the cert replacement you did.  It took some time before the cache got updated with the new version of the cert but looks like it eventually updated.

We wanted to separate internal server errors (500) from missing cert errors (404) that was why you were getting the 500 errors but it appears that you correctly pointed out that in the multicert disk case, the missing cert hash should have been a 404 error and not just an internal server error.  I will update the code to reflect this.  Thanks again for reporting.
